CREATE TABLE crime
(
Incident_Number INTEGER,
Highest_Offense_Description VARCHAR(20),
Highest_Offense_Code INTEGER,
Family_Violence VARCHAR(1),
Occurred_Date_Time DATETIME,
Occurred_Date DATE,
Occurred_Time TIME,
Report_Date_Time DATETIME,
Report_Date DATE,
Report_Time TIME,
Location_Type VARCHAR(30),
Address VARCHAR(50),
Zip_Code INTEGER,
Council_District VARCHAR(50),
APD_Sector VARCHAR(50),
APD_District VARCHAR(50),
PRA VARCHAR(50),
Census_Tract VARCHAR(50),
Clearance_Status VARCHAR(50),
Clearance_Date DATE,
UCR_Category VARCHAR(50),
Category_Description VARCHAR(50),
X_coordinate VARCHAR(50),
Y_coordinate VARCHAR(50),
Latitude VARCHAR(50),
Longitude VARCHAR(50),
Location VARCHAR(50)
)